#!/bin/sh
exec scala -savecompiled "$0" "$@"
!#

import scala.io.StdIn
import annotation.tailrec
import boundingboxes.core.Universe

@tailrec
def loop(line: String, u0: Universe): Universe =
  if (line == null) u0
  else loop(StdIn.readLine(), line.foldLeft(u0) { (u1, c) =>
    if (c == '*') u1.appendAsterisk
    else u1.appendDash
  })

val firstLine = StdIn.readLine()
val largestBoxes = loop(firstLine, Universe(firstLine.length)).largestNonoverlappingBoxes
largestBoxes.foreach(println)
System.exit(if (largestBoxes.isEmpty) -1 else 0)